### ISSUE TITLE
APC Information not showing in phpinfo

### ISSUE THREAD

**Issue by Nirjonadda** [krakjoe/apcu-bc#30] opened 2019-04-05 14:49 UTC
APC Information not showing in phpinfo page with v1.0.5 update.

phpinfo page with v1.0.4 this show about APC and APCu info.

![ScreenShot00997](https://user-images.githubusercontent.com/6899856/55636162-9402e380-57c2-11e9-8027-cc35726b2a71.png)

phpinfo page with v1.0.5 this show about only APCu, not APC info.

![ScreenShot00998](https://user-images.githubusercontent.com/6899856/55636220-b3017580-57c2-11e9-9e32-1ee8a011d985.png)

**Comment by remicollet** [comment] 2019-04-06 07:12
Sorry, cannot reproduce:

```
$ php -i
...

apc

APC Compatibility => 1.0.5

apcu

APCu Support => Enabled
Version => 5.1.17
...

```

**Comment by Nirjonadda** [comment] 2019-04-06 18:34
@remicollet Please can you check with PHP Version 7.3.3 installation? Also I think this happened with 1.0.5 because some php info removed. 


What has changed in 1.0.5?

```
- fix skipif.inc path in test suite
- remove APCU version from phpinfo
- remove Build date from phpinfo

```

**Comment by remicollet** [comment] 2019-04-08 05:52
Yes **apcu** version was removed from **apcu_bc** information, 

- because they are display below in **apcu** information (see my above paste)
- because they are related to _buildtime_, which is confusing for user when _runtime_ version is newer

**Comment by Nirjonadda** [comment] 2019-04-08 10:51
OK but why are not showing APC info? Do you checked out with PHP Version 7.3.3 installation?

**Comment by remicollet** [comment] 2019-04-08 11:20
> OK but why are not showing APC info?

No idea

```
php -v
php -m
php --ri apc
```

> Do you checked out with PHP Version 7.3.3 installation?

Yes, the paste above (well, 7.3.4 and also 7.2, 7.1 and 7.0)

**Comment by remicollet** [comment] 2019-04-25 12:18
No news, closing

**Closed as completed by remicollet** 2019-04-25 12:18 UTC
